export const PRODUCTS = [
  {
    id: 'tumbler-20',
    name: '20oz Engraved Tumbler',
    price: 28,
    category: 'drinkware',
    image: 'Engraved 20oz Tumbler',
    description:
      'Insulated stainless steel, keeps drinks hot or cold for hours. Add a name or monogram.',
  },
  {
    id: 'whiskey-pair',
    name: 'Whiskey Glass Set of 2',
    displayName: 'Whiskey Glass (set of 2)',
    price: 42,
    category: 'drinkware',
    image: 'Whiskey Glass',
    description:
      'Lead-free crystal. Pair set with custom initials or full text engraving.',
  },
  {
    id: 'flask-6',
    name: 'Stainless Hip Flask',
    price: 34,
    category: 'drinkware',
    image: 'Engraved Flask',
    description: '6oz with leather wrap option. Great groomsman gift.',
  },
  {
    id: 'board-walnut',
    name: 'Walnut Cutting Board',
    price: 65,
    category: 'wood',
    image: 'Walnut Cutting Board',
    description:
      '16" x 11", solid walnut, food-safe finish. Two lines of personalization.',
  },
  {
    id: 'board-charcuterie',
    name: 'Charcuterie Board',
    price: 95,
    category: 'wood',
    image: 'Charcuterie Board',
    description: 'Live-edge maple, 18". Engraved name or family crest.',
  },
  {
    id: 'coasters-4',
    name: 'Wood Coaster Set (4)',
    displayName: 'Wood Coaster Set',
    price: 22,
    category: 'wood',
    image: 'Coaster Set',
    description: 'Set of four, walnut with cork backing. Custom design or monogram.',
  },
  {
    id: 'sign-family',
    name: 'Family Established Sign',
    price: 85,
    category: 'signs',
    image: 'Family Name Sign',
    description: 'Reclaimed barn wood, 24"x12". Last name + year. Hangs ready.',
  },
  {
    id: 'sign-house',
    name: 'House Number Plaque',
    price: 55,
    category: 'signs',
    image: 'House Number Sign',
    description: 'Cedar, weather-treated. Number + street optional.',
  },
  {
    id: 'box-wedding',
    name: 'Wedding Keepsake Box',
    price: 78,
    category: 'gifts',
    image: 'Wedding Gift Box',
    description: 'Cherry wood, hinged. Names + date engraved on top.',
  },
  {
    id: 'memorial-pet',
    name: 'Pet Memorial Plaque',
    price: 48,
    category: 'gifts',
    image: 'Pet Memorial Plaque',
    description: 'Maple plaque with engraved silhouette, name, and dates.',
  },
  {
    id: 'byo-bottle',
    name: 'Bring-Your-Own Bottle Engraving',
    displayName: 'BYO Bottle Engraving',
    price: 45,
    category: 'drinkware',
    image: 'BYO Bottle Engraving',
    imageSrc: '/images/products/johnnie-walker-1.jpg',
    description:
      'Send us your favorite bottle — whiskey, wine, champagne — and we’ll laser-etch custom artwork directly into the glass. Retirement gifts, milestones, anniversaries. Starting at $45.',
  },
];

export const GALLERY = [
  {
    category: 'drinkware',
    image: 'Johnnie Walker Black Label',
    imageSrc: '/images/products/johnnie-walker-1.jpg',
    title: 'Custom Whiskey Bottle Engraving',
    desc: 'Limited-edition crest etched on a Johnnie Walker Black Label — retirement gift for a longtime supervisor.',
  },
  {
    category: 'drinkware',
    image: 'Johnnie Walker — Detail',
    imageSrc: '/images/products/johnnie-walker-2.jpg',
    title: 'Whiskey Bottle Engraving — Detail',
    desc: 'Close-up of the etched crest and personalized name plate.',
  },
  {
    category: 'drinkware',
    image: 'NJ State Police Glass',
    imageSrc: '/images/products/nj-state-police-glass.jpg',
    title: 'NJ State Police Rocks Glass',
    desc: 'Department badge etched on a square rocks glass — retirement and promotion gift staple.',
  },
  {
    category: 'drinkware',
    image: 'NYC DSNY M5 Glass',
    imageSrc: '/images/products/nyc-dsny-m5-glass.jpg',
    title: 'NYC DSNY "M5 For Life" Glass',
    desc: 'Department of Sanitation crest with custom "M5 For Life / Ride or Die" lockup — group order for a sanitation crew.',
  },
  {
    category: 'drinkware',
    image: 'First Mother’s Day Wine Glass',
    imageSrc: '/images/products/wine-glass-first-mothers-day.jpg',
    title: 'First Mother’s Day Wine Glass',
    desc: 'Stemmed wine glass etched with a delicate floral wreath and baby-feet motif.',
  },
  {
    category: 'drinkware',
    image: 'Love You to the Moon Glass',
    imageSrc: '/images/products/wine-glass-moon-back.jpg',
    title: '"To the Moon and Back" Stemless',
    desc: 'Stemless wine glass with mother-and-children silhouette and a personalized quote exchange.',
  },
  {
    category: 'drinkware',
    image: 'Prosecco — The Ortega’s',
    imageSrc: '/images/products/prosecco-ortega.jpg',
    title: 'Wedding Prosecco Bottle',
    desc: 'Custom wedding favor — sponsor logo with the couple’s name and est. date etched into the bottle.',
  },
  {
    category: 'wood',
    image: 'MOM Cutting Board',
    imageSrc: '/images/products/mom-cutting-board-studio.jpg',
    title: '"Mom — For All You Do" Cutting Board',
    desc: 'End-grain walnut board with a poem-style engraving and a personalized Christmas note from the kids.',
  },
  {
    category: 'wood',
    image: 'MOM Board — Outdoor',
    imageSrc: '/images/products/mom-cutting-board-outdoor.jpg',
    title: 'Mom Cutting Board — Checkered',
    desc: 'Checkered walnut/maple end-grain board with the same poem engraving. Same design, different blank.',
  },
  {
    category: 'other',
    image: 'Ray-Ban Meta Case — Featured',
    imageSrc: '/images/products/rayban-meta-case-1.jpg',
    title: 'Ray-Ban Meta Case — Custom Logo',
    desc: 'Personalized leather case engraving for the Ray-Ban Meta. Anonymous/Shrink’s Office Prague 2026 design.',
  },
  {
    category: 'other',
    image: 'Ray-Ban Meta Case — Closed',
    imageSrc: '/images/products/rayban-meta-case-2.jpg',
    title: 'Ray-Ban Meta Case — Detail',
    desc: 'Close-up of the snap-closure case with logo engraving.',
  },
  {
    category: 'other',
    image: 'Ray-Ban Meta Case — Open',
    imageSrc: '/images/products/rayban-meta-case-3.jpg',
    title: 'Ray-Ban Meta Case — Interior',
    desc: 'Open case showing the etched interior detail and finish.',
  },
  { category: 'drinkware', image: 'Engraved Tumbler — Monogram', title: 'Monogrammed 20oz', desc: 'Classic three-letter monogram, sandblasted finish.' },
  { category: 'drinkware', image: 'Whiskey Glass Set', title: 'Whiskey Glass Set', desc: 'Set of four with custom family crest.' },
  { category: 'wood', image: 'Walnut Cutting Board', title: 'Wedding Cutting Board', desc: 'Last names, wedding date, with botanical border.' },
  { category: 'wood', image: 'Charcuterie Board', title: 'Charcuterie Board', desc: 'Olive wood, custom recipe engraving.' },
  { category: 'signs', image: 'Family Name Sign', title: 'Established Sign', desc: 'Reclaimed barn wood with family name & year.' },
  { category: 'signs', image: 'Business Plaque', title: 'Storefront Plaque', desc: 'Cedar, weather-treated, mounted brass hardware.' },
  { category: 'gifts', image: 'Pet Memorial', title: 'Pet Memorial', desc: 'Hand-traced silhouette, name & dates.' },
  { category: 'gifts', image: 'Anniversary Plaque', title: 'Anniversary Keepsake', desc: 'Maple with full vow text engraved.' },
  { category: 'other', image: 'Leather Wallet', title: 'Leather Wallet', desc: 'Initials & coordinates on bifold.' },
  { category: 'other', image: 'Slate Coasters', title: 'Slate Coaster Set', desc: 'Set of six, custom logo. Felt-backed.' },
  { category: 'signs', image: 'Bar Sign', title: 'Home Bar Sign', desc: 'Reclaimed oak with metal accent strapping.' },
  { category: 'wood', image: 'Recipe Board', title: "Grandma's Recipe", desc: 'Handwriting traced from original recipe card.' },
];
