export const PRODUCTS = [
  {
    id: 'tumbler-20',
    name: '20oz Engraved Tumbler',
    price: 28,
    category: 'drinkware',
    image: 'Engraved 20oz Tumbler',
    description:
      'Insulated stainless steel, keeps drinks hot or cold for hours. Add a name or monogram.',
  },
  {
    id: 'whiskey-pair',
    name: 'Whiskey Glass Set of 2',
    displayName: 'Whiskey Glass (set of 2)',
    price: 42,
    category: 'drinkware',
    image: 'Whiskey Glass',
    description:
      'Lead-free crystal. Pair set with custom initials or full text engraving.',
  },
  {
    id: 'flask-6',
    name: 'Stainless Hip Flask',
    price: 34,
    category: 'drinkware',
    image: 'Engraved Flask',
    description: '6oz with leather wrap option. Great groomsman gift.',
  },
  {
    id: 'board-walnut',
    name: 'Walnut Cutting Board',
    price: 65,
    category: 'wood',
    image: 'Walnut Cutting Board',
    description:
      '16" x 11", solid walnut, food-safe finish. Two lines of personalization.',
  },
  {
    id: 'board-charcuterie',
    name: 'Charcuterie Board',
    price: 95,
    category: 'wood',
    image: 'Charcuterie Board',
    description: 'Live-edge maple, 18". Engraved name or family crest.',
  },
  {
    id: 'coasters-4',
    name: 'Wood Coaster Set (4)',
    displayName: 'Wood Coaster Set',
    price: 22,
    category: 'wood',
    image: 'Coaster Set',
    description: 'Set of four, walnut with cork backing. Custom design or monogram.',
  },
  {
    id: 'sign-family',
    name: 'Family Established Sign',
    price: 85,
    category: 'signs',
    image: 'Family Name Sign',
    description: 'Reclaimed barn wood, 24"x12". Last name + year. Hangs ready.',
  },
  {
    id: 'sign-house',
    name: 'House Number Plaque',
    price: 55,
    category: 'signs',
    image: 'House Number Sign',
    description: 'Cedar, weather-treated. Number + street optional.',
  },
  {
    id: 'box-wedding',
    name: 'Wedding Keepsake Box',
    price: 78,
    category: 'gifts',
    image: 'Wedding Gift Box',
    description: 'Cherry wood, hinged. Names + date engraved on top.',
  },
  {
    id: 'memorial-pet',
    name: 'Pet Memorial Plaque',
    price: 48,
    category: 'gifts',
    image: 'Pet Memorial Plaque',
    description: 'Maple plaque with engraved silhouette, name, and dates.',
  },
];

export const GALLERY = [
  { category: 'drinkware', image: 'Engraved Tumbler — Monogram', title: 'Monogrammed 20oz', desc: 'Classic three-letter monogram, sandblasted finish.' },
  { category: 'drinkware', image: 'Whiskey Glass Set', title: 'Whiskey Glass Set', desc: 'Set of four with custom family crest.' },
  { category: 'wood', image: 'Walnut Cutting Board', title: 'Wedding Cutting Board', desc: 'Last names, wedding date, with botanical border.' },
  { category: 'wood', image: 'Charcuterie Board', title: 'Charcuterie Board', desc: 'Olive wood, custom recipe engraving.' },
  { category: 'signs', image: 'Family Name Sign', title: 'Established Sign', desc: 'Reclaimed barn wood with family name & year.' },
  { category: 'signs', image: 'Business Plaque', title: 'Storefront Plaque', desc: 'Cedar, weather-treated, mounted brass hardware.' },
  { category: 'gifts', image: 'Pet Memorial', title: 'Pet Memorial', desc: 'Hand-traced silhouette, name & dates.' },
  { category: 'gifts', image: 'Anniversary Plaque', title: 'Anniversary Keepsake', desc: 'Maple with full vow text engraved.' },
  { category: 'other', image: 'Leather Wallet', title: 'Leather Wallet', desc: 'Initials & coordinates on bifold.' },
  { category: 'other', image: 'Slate Coasters', title: 'Slate Coaster Set', desc: 'Set of six, custom logo. Felt-backed.' },
  { category: 'signs', image: 'Bar Sign', title: 'Home Bar Sign', desc: 'Reclaimed oak with metal accent strapping.' },
  { category: 'wood', image: 'Recipe Board', title: "Grandma's Recipe", desc: 'Handwriting traced from original recipe card.' },
];
